### ISSUE TITLE
Add Brew support for easier installation

### ISSUE THREAD

**Issue by dnivra26** [alaminopu/kctl#2]
Brew supports third party taps. https://docs.brew.sh/Taps

**Comment by dnivra26** [comment]
Hi @alaminopu , i got started with this task. As a starting step we need the binaries in github releases. I have created a pull request #3  that has travis ci config to do that. Take a look.

**Comment by dnivra26** [comment]
@alaminopu  Done. Have created pull request #4 for homebrew support. More details in the pull request.

**Comment by alaminopu** [comment]
@dnivra26  Thanks for working on it.
