### ISSUE TITLE
Support setting namespace on the fly

### ISSUE THREAD

**Issue by alaminopu** [alaminopu/kctl#5]
Currently, the namespace is defined as [hard coded ](https://github.com/alaminopu/kctl/blob/master/src/main.rs#L9). 

Planning to set the namespace with a command 

```
kctl set-namespace -n <namespace>
```

Example: 
```
kctl set-namespace -n food
```

Save namespace value in the config `~/.kctlconf` 

Read the namespace value from config `~/.kctlconf`

**Comment by dnivra26** [comment]
Hey @alaminopu , with the namespace hardcoded it is impossible to use the tool. For now i have added an optional argument -n or --namespace to specify the namespace. We can remove it when you are done with your changes.

**Comment by alaminopu** [comment]
@dnivra26  That works for now!

**Comment by alaminopu** [comment]
@dnivra26  keeping your changes along with the new feature.
