### ISSUE TITLE
Decouple clap from the core logic

### ISSUE THREAD

**Issue by dnivra26** [alaminopu/kctl#7]
Right now the core logic has clap tightly coupled with it. Planning to move it out and make the core logic independent of clap

**Comment by dnivra26** [comment]
Working on it

**Comment by alaminopu** [comment]
@dnivra26 Good changes! In future, I am thinking maybe we can separate each command in a separate file. what do you think?

**Comment by dnivra26** [comment]
Yeah we should do it. The main file is too big now. We need to also add tests.

**Comment by alaminopu** [comment]
Created a new issue for that. Maybe we can close this one?

**Comment by dnivra26** [comment]
Yes
